spring.application.name=SideProject01


#?? DB
#spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://10.137.1.164:5432/test
spring.datasource.username=drone_fmc_user
spring.datasource.password=1234